# Embeds text files as C++ raw string constants: generates a header defining
#   namespace <ns> { inline constexpr std::string_view <name> = R"__IFORGE__(...)";
# for each input file. Raw strings keep the sources byte-identical; the
# sentinel delimiter is chosen to never appear in InfraForge shader sources.
# Usage:
#   cmake -DOUT=<header> -DNS=<namespace> -DNAME_<i>=<var> -DFILE_<i>=<path> -P EmbedTextFiles.cmake

file(WRITE "${OUT}" "// @generated by EmbedTextFiles.cmake; do not edit.\n#pragma once\n\n#include <string_view>\n\nnamespace ${NS} {\n\n")

set(index 0)
while(DEFINED NAME_${index} AND DEFINED FILE_${index})
    set(name "${NAME_${index}}")
    set(file "${FILE_${index}}")
    file(READ "${file}" content)
    set(line "inline constexpr std::string_view ${name} = R\"__IFORGE__(${content})__IFORGE__\";\n\n")
    file(APPEND "${OUT}" "${line}")
    math(EXPR index "${index} + 1")
endwhile()

file(APPEND "${OUT}" "} // namespace ${NS}\n")
